-- SELECT COMMANDS--
SELECT * FROM CUSTOMER;
SELECT CUSTOMER_ID ,CUS_NAME,CUS_SALARY
FROM CUSTOMER;
SELECT CUSTOMER_ID ,CUS_NAME,CUS_SALARY
FROM customer
WHERE CUS_SALARY BETWEEN 100000 AND 160000;

SELECT * FROM customer
WHERE CUS_SALARY >50000 AND CUS_SALARY <150000 AND CUS_LOCATION IN ('CHENNAI','COIMBATORE');

SELECT CUS_LOCATION,COUNT(CUSTOMER_ID) AS TOTAL_MEMBERS
FROM customer
GROUP BY CUS_LOCATION;

SELECT CUS_LOCATION,AVG(CUS_SALARY) AS AVERAGE_SALARY
FROM customer
WHERE CUS_SALARY >50000
GROUP BY `CUS_LOCATION`
HAVING AVERAGE_SALARY>80000
ORDER BY AVERAGE_SALARY DESC
LIMIT 0,2;
