CREATE TABLE EMPLOYEE (
    EM_ID INT PRIMARY KEY,
    EM_NAME VARCHAR(100) NOT NULL,
    EM_EMAIL VARCHAR(100)NOT NULL,
    EM_AGE INT CHECK( EM_AGE BETWEEN 20 AND 55));

    SELECT * FROM EMPLOYEE;

    --ALTER COMMANDS 

    ALTER TABLE EMPLOYEE ADD COLUMN
    EM_SALARY DECIMAL(10,2) NOT NULL;

    ALTER TABLE EMPLOYEE ADD COLUMN
    EM_PHONE INT(10) UNIQUE NOT NULL ;

    ALTER TABLE EMPLOYEE MODIFY COLUMN
    EM_AGE INT CHECK(EM_AGE BETWEEN 19 AND 55) NOT NULL;

    ALTER TABLE EMPLOYEE DROP COLUMN
    EM_PHONE;

    ALTER TABLE EMPLOYEE RENAME COLUMN
    EM_PHONE TO EM_MOBILE_NUMBER;
    