CREATE TABLE EMPLOYEE (
    EM_ID INT PRIMARY KEY,
    EM_NAME VARCHAR(100) NOT NULL,
    EM_EMAIL VARCHAR(100)NOT NULL,
    EM_AGE INT CHECK( EM_AGE BETWEEN 20 AND 55));

    SELECT * FROM EMPLOYEE;

    --ALTER COMMANDS 

    ALTER TABLE EMPLOYEE ADD COLUMN
    EM_SALARY DECIMAL(10,2) NOT NULL;

    ALTER TABLE EMPLOYEE ADD COLUMN
    EM_PHONE INT(10) UNIQUE NOT NULL ;

    ALTER TABLE EMPLOYEE MODIFY COLUMN
    EM_AGE INT CHECK(EM_AGE BETWEEN 19 AND 55) NOT NULL;

    ALTER TABLE EMPLOYEE DROP COLUMN
    EM_PHONE;

    ALTER TABLE EMPLOYEE RENAME COLUMN
    EM_PHONE TO EM_MOBILE_NUMBER;
-- ADD CONSTRAINT

ALTER TABLE EMPLOYEE ADD CONSTRAINT
PK_EM_MOBILE_NUMBER PRIMARY KEY(EM_MOBILE_NUMBER);

-- DML
INSERT INTO EMPLOYEE VALUES(1,'GOPAL','gopal@gmail.com',21,30000,1112223334);

INSERT INTO employee VALUES(2,'DHANAPAL','dhanapal@gmail.com',22,35000,991444679),
(3,'GOPIKA','gopika@gmail.com',21,35000,337733399);

UPDATE employee
SET `EM_MOBILE_NUMBER`=412345678
WHERE EM_ID=3;

DELETE FROM EMPLOYEE 
WHERE EM_AGE=21;