SELECT  * FROM customer
WHERE CUS_LOCATION ='CHENNAI'OR CUS_LOCATION='COIMBATORE';

SELECT * FROM customer
WHERE CUS_LOCATION!='BANGALORE';

SELECT * FROM customer
WHERE CUS_SALARY > 50000;

SELECT * FROM customer
WHERE NOT  CUS_LOCATION IN('CHENNAI','COIMBATORE');

SELECT * FROM customer
WHERE NOT  CUS_SALARY <50000;

SELECT * FROM CUSTOMER
WHERE CUSTOMER_ID BETWEEN 5 AND 9 OR CUSTOMER_ID BETWEEN 11 AND 13;



