CREATE TABLE CUSTOMER(
    CUSTOMER_ID INT PRIMARY KEY,
    CUS_NAME VARCHAR(100) NOT NULL,
    CUS_EMAIL VARCHAR(100)UNIQUE NOT NULL,
    CUS_SALARY DECIMAL(10,2) NOT NULL,
    CUS_LOCATION VARCHAR(100) NOT NULL
)

SELECT * FROM client;

DROP TABLE CUSTOMER;

-- \ ALTER TABLE COMMANDS/
--ADD--
ALTER TABLE CUSTOMER ADD
CUS_PHONE VARCHAR(10) NOT NULL;

--MODIFY
ALTER TABLE CUSTOMER MODIFY CUS_PHONE VARCHAR(10) UNIQUE NOT NULL;

--drop
ALTER TABLE CUSTOMER DROP COLUMN CUS_PHONE;

--RENAME
ALTER TABLE CUSTOMER RENAME COLUMN CUS_PH_NUM TO CUS_PHONE_NUMBER;

--TRUNCATE
TRUNCATE TABLE CUSTOMER;

---RENAME TABLE
ALTER TABLE CUSTOMER RENAME TO CLIENT;