CREATE TABLE CUSTOMER(
    CUSTOMER_ID INT PRIMARY KEY,
    CUS_NAME VARCHAR(100) NOT NULL,
    CUS_EMAIL VARCHAR(100)UNIQUE NOT NULL,
    CUS_SALARY DECIMAL(10,2) NOT NULL,
    CUS_LOCATION VARCHAR(100) NOT NULL
)

SELECT * FROM CUSTOMER;