CREATE TABLE CUSTOMER(
    CUSTOMER_ID INT PRIMARY KEY,
    CUS_NAME VARCHAR(100) NOT NULL,
    CUS_EMAIL VARCHAR(100)UNIQUE NOT NULL,
    CUS_SALARY DECIMAL(10,2) NOT NULL,
    CUS_LOCATION VARCHAR(100) NOT NULL
)

SELECT * FROM client;

DROP TABLE CLIENT;

-- \ ALTER TABLE COMMANDS/
--ADD--
ALTER TABLE CUSTOMER ADD
CUS_STATUS VARCHAR(10) NOT NULL;

--MODIFY
ALTER TABLE CUSTOMER MODIFY CUS_PHONE VARCHAR(10) UNIQUE NOT NULL;

--drop
ALTER TABLE CUSTOMER DROP COLUMN CUS_PHONE;

--RENAME
ALTER TABLE CUSTOMER RENAME COLUMN CUS_PH_NUM TO CUS_PHONE_NUMBER;

--TRUNCATE
TRUNCATE TABLE CUSTOMER;

---RENAME TABLE
ALTER TABLE CUSTOMER RENAME TO CLIENT;

create table p_id(
    p_id varchar(100)not null,
    p_name varchar(100) not null,
    p_price decimal(10,2) not null);

    /* ALTER TABLE  table_name 
    ADD CONSTRANT constraint_name 
    constarint_type(column_name) */

    ALTER TABLE p_id
    ADD CONSTRAINT pk_pk_id
    PRIMARY KEY(p_id);
     select * from p_id;

     ALTER TABLE p_id
     ADD CONSTRAINT UQ_p_name
     UNIQUE(p_name);

ALTER TABLE p_id
ADD CONSTRAINT chk_P_price
CHECK(p_price>0)